types:
  HEAD:
    sign-format:
    - '&f%name%'
    - '&e#%rank%'
    - '&a%value% &f%identifier%'
    - '&9&m-------------'
  HOLOGRAM:
    header: '&9&m-------&r &7Top &f10 &7%type% &9&m-------&r'
    line-format: '&e%rank%. &f%name% &7- &a%value% &7%identifier%'
    footer: '&9&m-------&r &7Top &f10 &7%type% &9&m-------&r'
    space-between-lines: 0.03
  SIGN:
    header: '&fTop &910 &f%type%'
    space-between: true
    loading: '&cLoading players...'
    no-data: '&cNot enough data.'
    sign-line-format: '&e#%rank% %name%'