# Hooks into HolographicDisplays for hologram leaderboards if available on the server.
# default: true
hook-into-holographicdisplays: true

# Interval to check '/duel top' for change and update head, hologram, and sign leaderboards accordingly.
# default: 30
change-check-interval: 30

# One of the following prefixes will be applied to a player's displayed name on the HOLOGRAM leaderboard if the group name matches.
# NOTE: Vault is required for this option to work!
prefixes:
  enabled: true

  # NOTE: The extension will only check for player's primary group name!
  groups:
    owner: '&4[OWNER] '
    admin: '&c[ADMIN] '
    moderator: '&e[MOD] '
    helper: '&a[HELPER] '
    vip: '&6[VIP] '

types:
  HEAD:
    loading: '&cLoading...'
    no-data: '&cNo data.'
    sign-format:
    - '&f%name%'
    - '&e#%rank%'
    - '&a%value% &f%identifier%'
    - '&9&m-------------'
  HOLOGRAM:
    loading: '&cLeaderboard is loading...'
    no-data: '&cNo data available.'
    header: '&9&m-------&r &7Top &f10 &7%type% &9&m-------&r'
    line-format: '&e%rank%. &f%name% &7- &a%value% &7%identifier%'
    footer: '&9&m-------&r &7Top &f10 &7%type% &9&m-------&r'
    space-between-lines: 0.05
  SIGN:
    loading: '&cLoading...'
    no-data: '&cNo data.'
    header: '&fTop &910 &f%type%'
    space-between: true
    sign-line-format: '&e#%rank% %name%'

placeholders:
  # Define the text to return if rank placeholder is called for player that is not on the leaderboard.
  no-rank: 'Unranked'

  # Define the text to return if data is still loading for the placeholder.
  loading: 'Loading...'

  # Define the text to return if no data was found for the placeholder.
  no-data: 'No data.'